---
functional:
  - Возможность соревноваться двум игрокам в решении задач
  - Возможность наблюдать за кодом соперника в реальном времени
  - Возможность игры с ботом
  - Возможность пригласить друга по ссылке
  - Наличие рейтинговой системы

non-functional:
  - Сайт должен быть разработан с учетом удобства использования (usability)
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - Требования могут дополняться и изменяться сообществом в процессе разработки
  - Код проекта должен быть открытым (open-source) и доступным для вклада сообщества
  - Проект должен иметь каналы обратной связи с пользователями (например, Telegram-канал)
