---
functional:
  - Возможность соревноваться двум игрокам в решении задач
  - Возможность наблюдать за кодом соперника в реальном времени
  - Возможность игры с ботом
  - Возможность пригласить друга по ссылке
  - Наличие рейтинговой системы
  - Возможность авторизации пользователя
  - Возможность создания новой игры (кнопка "Create game")
  - Возможность подключения ко входящей игре (кнопка "Connect to game")
  - Отображение списка доступных игр для подключения
  - Отображение состояния ожидания второго игрока
  - Отображение двух редакторов кода (своего и соперника)
  - Отображение таймера игры и задания
  - Возможность проверки решения кнопкой "Check" с неограниченным числом попыток
  - Автоматическое определение победителя при правильном решении
  - Отображение модального окна с результатом (победитель/проигравший)
  - Возможность выхода из игры (кнопка "Exit")
  - Возможность переподключения в игру при потере соединения
  - Автоматическое завершение игры при выходе обоих игроков
  - Возможность наблюдения за кодом после завершения игры (до выхода)

non-functional:
  - Сайт должен быть разработан с учетом удобства использования (usability)
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть адаптирован под мобильные устройства
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Игра должна корректно обрабатывать потери соединения и позволять переподключение
  - Интерфейс должен обновляться в реальном времени без перезагрузки страницы
  - Время отклика между игроками не должно превышать 1 секунды
  - Должна быть реализована система логирования (ошибки, события, победы/поражения)
  - Код должен быть покрыт автоматическими тестами (юнит, интеграционными и end-to-end)
  - Сервис должен быть масштабируемым (возможность добавления новых серверов без простоев)

implicit:
  - Требования могут дополняться и изменяться сообществом в процессе разработки
  - Код проекта должен быть открытым (open-source) и доступным для вклада сообщества
  - Проект должен иметь каналы обратной связи с пользователями (например, Telegram-канал)
  - Игровая логика и правила должны быть документированы
  - Интерфейс и тексты должны поддерживать мультиязычность
  - Архитектура должна позволять добавление новых игровых режимов (например, командные сражения, турниры)
  - Все данные об играх и результатах должны сохраняться в базе данных
  - При ошибках (например, потеря соединения) пользователю должно отображаться понятное сообщение
